### PR TITLE
Making the card smaller and the icon bigger

### PR DESCRIPTION
**Pull request by ZeyadTarekk**

### CODE REVIEW

**Comment by hreyesm** [comment]
Looking great! Image is still squeezing for me, though.

Screen Shot 2022-07-04 at 18 35 20

**Comment by hreyesm** [comment]
Not sure if it's just me, but there seems to be a few cases where content inside `Card` keeps overflowing. Same happens with `FeaturedBountyCard`. Can you test if it happens to you too? @ZeyadTarekk  @HaresMahmood 

Screen Shot 2022-07-04 at 18 37 40

**Comment by ZeyadTarekk** [comment]
I didn't work on the mobile version yet @hreyesm

**Comment by HaresMahmood** [comment]
Thanks for adding `gap-2` to the `Chip`s - I'm approving this since it's meant to resemble the Figma for now, the responsive version can be added later.

**Review by HaresMahmood — APPROVED** [review]

**Pull request merged**
