### PR TITLE
Add `Text`-component with standardized styling.

### PR DESCRIPTION
**Pull request by HaresMahmood**
# Overview

Add a `Text`-component (`/components/common/text/`) with standardized styling based on the [Figma prototype](https://www.figma.com/file/sNkHueU0kTpW4FAWoIfhPN/Solana-Bounty?node-id=0%3A1).

## Features

- 7 variants:
   - `hero`
   - `big-heading`
    - `heading`
    - `sub-heading`
    - `paragraph`
    - `input`
    - `label`
- Includes `className` `prop` for customization..

## Example

Snippet from: `src/components/home-page/actions-section/index.tsx`.
```jsx
<div className="...">
    <Text variant="big-heading">
        Fund a Bounty
    </Text>
    <Text variant="paragraph" className="text-gray-500">
        Lorem ipsum dolor sit amet, <span className="text-primary">consectetur</span> adipiscing elit.
    </Text>
</div>         
```
image

# Screenshots

image

### CODE REVIEW

**Comment by hreyesm** [comment]
Looks great! My only concern is: doesn't using the HTML `<text>` tag for all variants makes things less accessible than, say, using `<h1>` for `hero`, `<h2>` for `heading`, to name a few? It would be awesome to have a way to declare the semantic meaning of each `<Text />` element via an `as` prop, e.g., by calling `<Text as="h1" variant="big-heading />`. That, I think, could be easily done with the React API [`createElement()`](https://reactjs.org/docs/react-api.html#createelement) function. 

Let me know your thoughts on this.

**Comment by HaresMahmood** [comment]
> Looks great! My only concern is: doesn't using the HTML `<text>` tag for all variants makes things less accessible than, say, using `<h1>` for `hero`, `<h2>` for `heading`, to name a few? It would be awesome to have a way to declare the semantic meaning of each `<Text />` element via an `as` prop, e.g., by calling `<Text as="h1" variant="big-heading" />`. For ease of use, we could also assign a default tag to each variant where it makes sense (in the case of `paragraph`, for example, we would normally want to render a `<p>` tag). That, I think, could be easily done by leveraging the React API [`createElement()`](https://reactjs.org/docs/react-api.html#createelement) function.
> 
> Let me know your thoughts on this.

I think that while it would offer extra flexibility, it wouldn't necessarily change anything from a visual standpoint, since [headings in Tailwind are completely unstyled](https://tailwindcss.com/docs/preflight#headings-are-unstyled). I'll look `createElement()` though, and if you think this is something really necessary or important just let me know!

**Comment by hreyesm** [comment]
> 

Agree. I'll create an issue to address accessibility concerns in a separate PR.

**Review by WilliamWang2002 — COMMENTED** [review]
What about we add a global CSS file to style text instead of creating components?

**Comment by HaresMahmood** [comment]
> What about we add a global CSS file to style text instead of creating components?

Yes, but that would defeat the purpose of using Tailwind. The current approach is consistent with how other components (`Card`, `Button`, etc...) are implemented as well.

**Comment by HaresMahmood** [comment]
Please add this component to your previous work in the [`refactor/standardized-text` branch](/andresmgsl/solana-cohort-june-2022/tree/refactor/standardized-text) @WilliamWang2002 @ZeyadTarekk.

**Comment by HaresMahmood** [comment]
Still waiting for your changes @WilliamWang2002.

**Comment by HaresMahmood** [comment]
@WilliamWang2002 No need to go back and edit your stuff anymore - PR #77 aims to make the `Hero`-section more responsive, so I've replaced all text there as well.

**Comment by HaresMahmood** [comment]
(@hreyesm @WilliamWang2002 @ZeyadTarekk @HaresMahmood) Is it okay if everyone goes back to their previously edited stuff and resolves all merge conflicts that have recently been introduced? I don't want to break anything by doing it myself.

**Pull request closed without merging**
